# syntax=docker/dockerfile:1

FROM ros:jazzy-ros-base

ARG DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Install everything in ONE layer
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-jazzy-turtlesim \
    ros-jazzy-mavros \
    ros-jazzy-mavros-extras \
    geographiclib-tools \
    python3-colcon-common-extensions \
    python3-pip \
    git \
    locales \
    tmux \
    && locale-gen en_US.UTF-8 \
    && update-locale LANG=en_US.UTF-8 \
    && geographiclib-get-geoids egm96-5 \
    && rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

WORKDIR /ros2_ws

# Source ROS automatically
RUN echo "source /opt/ros/jazzy/setup.bash" >> /etc/bash.bashrc

CMD ["bash"]